findit/findit/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('jobs/', include('jobs.urls')),
    path('admin/', admin.site.urls),
]

findit/jobs/urls.py
from django.urls import path

from . import views

app_name = 'jobs'
urlpatterns = [
    # ex: /jobs/
    path('', views.all_jobs, name='all_jobs'),
    # ex: /jobs/1/
    path('<int:job_id>/', views.job_detail, name='job_detail'),
]

findit/jobs/models.py
from django.db import models


class Company(models.Model):
    name = models.CharField(max_length=50)
    city = models.CharField(max_length=50, default=None, blank=True)
    state = models.CharField(max_length=2, default=None, blank=True)
    about = models.CharField(max_length=1000, default=None, blank=True)
    embed_link = models.CharField(max_length=300, null=True, default=None, blank=True)


class Job(models.Model):
    title = models.CharField(max_length=50)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, blank=True, null=True, default=None)
    description = models.CharField(max_length=1000)
    link = models.CharField(max_length=300)


class Requirement(models.Model):
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    description = models.CharField(max_length=100)


class Experience(models.Model):
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    description = models.CharField(max_length=100)


class Compensation(models.Model):
    job = models.ForeignKey(Job, on_delete=models.CASCADE)
    description = models.CharField(max_length=100)

findit/jobs/views.py
from django.shortcuts import render, get_object_or_404


from .models import Job, Company, Requirement, Experience, Compensation


def all_jobs(request):
    all_jobs = Job.objects.all()
    context = {
        'all_jobs': all_jobs,
    }
    return render(request, 'jobs/index.html', context)


def job_detail(request, job_id):
    job = get_object_or_404(Job, pk=job_id)
    company = job.company
    requirements = Requirement.objects.filter(job=job)
    experiences = Experience.objects.filter(job=job)
    compensation = Compensation.objects.filter(job=job)

    context = {
        'job': job,
        'company': company,
        'requirements': requirements,
        'experiences': experiences,
        'compensation': compensation,
        'logo_path': 'jobs/'+ company.name + '.jpg'
    }
    return render(request, 'jobs/job_detail.html', context)

findit/jobs/templates/jobs/base.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'jobs/style.css' %}">

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">    
</head>
<body id="body-overrides">
    <div class="container" id="title">
        <div class="jumbotron" id="jumbotron-overrides">
            <a id="findit" href="{% url 'jobs:all_jobs'%}"> Find It </a>
            <p>The website that finds the right job for you.</p>
        </div>
    </div>
    {% block index %}
    {% endblock %}
</body>

</html>

findit/jobs/templates/jobs/index.html
{% extends "./base.html" %}
{% load static %}

{% block index %}

{% if all_jobs %}
    <div class="container jobs">
        <div class="row border-top"></div>
            {% for job in all_jobs %}
                <div class="row job" id="job-name-in">
                    <div class="col-sm-6" id="job-name">{{job.company.name}}</div>
                    <div class="col-sm-6" id="job-in"> THIS JOB IS IN</div>
                </div>
                <div class="row job" id="job-title-loc">
                        <div class="col-sm-6" id="job-title"><a href="{% url 'jobs:job_detail' job.id %}">{{job.title}}</a></div>
                        <div class="col-sm-6" id="job-loc"> {{job.company.city}} , {{job.company.state}}</div>
                </div>
            {% endfor %}
        <div class="row border-bottom"></div>
    </div>
{% else %}
    <p>No jobs available</p>
{% endif %}
{% endblock %}

findit/jobs/templates/jobs/job_detail.html
{% extends "./base.html" %}
{% load static %}

{% block index %}

<div class="container jobs">
    <div class="row border-top"></div>
    <div class="row job-detail">
        <div class="col-sm-6" id="job-detail-title">{{job.title}}</div>
        <div class="col-sm-6" id="logo">
            <img src= "{% static "" %}{{logo_path}}" alt="" width="75em" height="30em">
        </div>
    </div>
    <div class="row job-detail">
        <div class="col-sm-6" id="job-detail-name">{{company.name}}</div>
        <div class="col-sm-6">{{company.city}}, {{company.state}}</div>
    </div>
    <div class="row job-detail">
        <div class="col-sm-6" id="about"> ABOUT: </div>
    </div>
    <div class="row job-detail">
        <div class="col-sm-12" id="about-description"> {{company.about}}</div>
    </div>
    <div class="row job-detail">
        <div class="col-sm-6" id="job-description-title"> DESCRIPTION: </div>
    </div>
    <div class="row job-detail">
        <div class="col-sm-12" id="job-description"> {{job.description}}</div>
    </div>
    <div class="row job-detail">
        <div class="col-sm-12" id="job-description"> 
            <a href="{{job.link}}"> {{job.link}} </a>
        </div>
    </div>
    <div class="row job-detail">
        <div class="col-sm-6" id="job-requirements"> REQUIREMENTS:</div>
    </div>
    {% for requirement in requirements %}
        <div class="row job-detail">
            <div class="col-sm-12">{{requirement.description}}</div>
        </div>
    {% endfor %}
    <div class="row job-detail">
        <div class="col-sm-6" id="job-experience"> EXPERIENCE:</div>
    </div>
    {% for experience in experiences %}
        <div class="row job-detail">
            <div class="col-sm-12">{{experience.description}}</div>
        </div>
    {% endfor %}
    <div class="row job-detail">
        <div class="col-sm-6" id="comp"> COMPENSATION:</div>
    </div>
    {% for comp in compensation %}
        <div class="row job-detail">
            <div class="col-sm-12" id="comp-des">{{comp.description}}</div>
        </div>
    {% endfor %}
    <div class= "row job-detail">
        <div class="col-sm-12">
            <iframe align="middle" width="500" height="400" src="{{company.embed_link}}" frameborder="0" 
            allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
    </div>
    <div class="row border-bottom"></div>
</div>
{% endblock %}